ALTER TABLE ORDERS ADD ITEM_QUANTITY_COMBO VARCHAR(30);

ALTER TABLE STOCK ADD STOCK VARCHAR(30);

CREATE TABLE ITEM_QUANTITY_COMBO (
ITEM_QUANTITY_ID INT(10) AUTO_INCREMENT PRIMARY KEY,
ITEM_ID INT(10),
QUANTITY INT(10)
);
