 ALTER TABLE CUSTOMERS ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);
 ALTER TABLE ORDERS ADD DELIVERY_DATE DATE NOT NULL;
 ALTER TABLE ORDERS ADD FOREIGN KEY (ITEM_QUANTITY_ID) REFERENCES ITEM_QUANTITY_COMBO (ITEM_QUANTITY_ID);