 ALTER TABLE CUSTOMERS ADD ORDER_ID INT(10) UNSIGNED NOT NULL;
 ALTER TABLE CUSTOMERS ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);
 ALTER TABLE ORDERS ADD DELIVERY_DATE DATE NOT NULL;
 ALTER TABLE ITEM_QUANTITY_COMBO MODIFY  ITEM_QUANTITY_ID INT(10) UNSIGNED AUTO_INCREMENT;
 ALTER TABLE ORDERS ADD ITEM_QUANTITY_ID INT(10) UNSIGNED;
 ALTER TABLE ORDERS ADD FOREIGN KEY (ITEM_QUANTITY_ID) REFERENCES ITEM_QUANTITY_COMBO (ITEM_QUANTITY_ID);

