CREATE TABLE STOCK_ENTRY_DATA (
STOCK_ENTRY_DATA_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
QUANTITY INT(10) );

ALTER TABLE STOCK_ENTRY_DATA ADD ITEM_ID INT(10) UNSIGNED;
ALTER TABLE STOCK_ENTRY_DATA ADD FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ITEM_ID);



CREATE TABLE STOCK_STOCK_OVERVIEW (stock_stock_id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
STOCK_OVERVIEW_STOCK_ENTRY_DATA_ID INT(10)
);