CREATE TABLE ADMINS (
ADMIN_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(20) NOT NULL
);

ALTER TABLE CUSTOMERS
ADD E_MAIL VARCHAR(20) NOT NULL,
ADD ADDRESS VARCHAR(30) NOT NULL,
ADD PHONE_NUMBER VARCHAR(20) NOT NULL,
CHANGE NAME FIRST_NAME VARCHAR(20) NOT NULL;
